services:
  - type: web
    name: face-attendance
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend/app app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: face-attendance-db
          key: connectionString

databases:
  - name: face-attendance-db
    plan: free
