services:
  - type: web
    name: attendance-face-recog
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString

databases:
  - name: attendance-db
    plan: free
    region: oregon
